Peekpa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.bloguser.urls')),  # 新添加 BlogUser App URL 文件
    path('', include('apps.post.urls')),
]

apps/cms/urls.py
from django.urls import path
from . import views
from apps.cms.category_view import CategoryView
from apps.cms.category_view import CategoryEditView
from apps.cms.category_view import CategoryDeleteView
from apps.cms.post_view import PostView
from apps.cms.post_view import PostEditView
from apps.cms.post_view import PostDeleteView
from .link_view import LinkView
from .link_view import LinkEditView
from .link_view import LinkDeleteView
from .advertise_view import AdvertiseView
from .advertise_view import AdvertiseEditView
from .advertise_view import AdvertiseDeleteView
from .user_view import UserView
from .user_view import UserEditView
from .user_view import UserDeleteView

app_name = "cms"

urlpatterns = [
    path("login/", views.cms_login, name="login"),
    path("dashboard/", views.cms_dashboard, name="dashboard"),
    path("dashboard/category/manage", views.category_manage_view, name="category_manage_view"),
    path("dashboard/category/publish", views.category_publish_view, name="category_publish_view"),
    path("dashboard/category/add", CategoryView.as_view(), name="category_add"),
    path("dashboard/category/edit", CategoryEditView.as_view(), name="category_edit_view"),
    path("dashboard/category/delete", CategoryDeleteView.as_view(), name="category_delete"),
    path("dashboard/post/manage", views.post_manage_view, name="post_manage_view"),
    path("dashboard/post/publish", views.post_publish_view, name="post_publish_view"),
    path("dashboard/post/add", PostView.as_view(), name="post_add"),
    path("dashboard/post/edit", PostEditView.as_view(), name="post_edit_view"),
    path("dashboard/post/delete", PostDeleteView.as_view(), name="post_delete"),
    path("dashboard/link/manage", views.link_manage_view, name="link_manage_view"),
    path("dashboard/link/publish", views.link_publish_view, name="link_publish_view"),
    path("dashboard/link/add", LinkView.as_view(), name="link_add"),
    path("dashboard/link/edit", LinkEditView.as_view(), name="link_edit_view"),
    path("dashboard/link/delete", LinkDeleteView.as_view(), name="link_delete"),
    path("dashboard/advertise/manage", views.advertise_manage_view, name="advertise_manage_view"),
    path("dashboard/advertise/publish", views.advertise_publish_view, name="advertise_publish_view"),
    path("dashboard/advertise/add", AdvertiseView.as_view(), name="advertise_add"),
    path("dashboard/advertise/edit", AdvertiseEditView.as_view(), name="advertise_edit_view"),
    path("dashboard/advertise/delete", AdvertiseDeleteView.as_view(), name="advertise_delete"),
    path("dashboard/user/manage", views.user_manage_view, name="user_manage_view"),
    path("dashboard/user/publish", views.user_publish_view, name="user_publish_view"),
    path("dashboard/user/add", UserView.as_view(), name="user_add"),
    path("dashboard/user/edit", UserEditView.as_view(), name="user_edit_view"),
    path("dashboard/user/delete", UserDeleteView.as_view(), name="user_delete"),
]

apps/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("list/", views.post_list_view, name="post_list"),
    path("detail/<int:time_id>/", views.detail, name="detail"),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/post/models.py
from django.db import models
import markdown
import random
import datetime


class Category(models.Model):
    name = models.CharField(max_length=100)
    create_time = models.DateTimeField(auto_now_add=True)


class Post(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_DRAFT = 2
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
        (STATUS_DRAFT, '草稿'),
    )
    title = models.CharField(max_length=200)
    author = models.ForeignKey('bloguser.User', on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    content_html = models.TextField(blank=True, editable=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    priority = models.IntegerField(default=-1)
    is_hot = models.BooleanField(default=False)
    status = models.PositiveIntegerField(default=STATUS_DRAFT, choices=STATUS_ITEMS)
    publish_time = models.DateTimeField(auto_now_add=True)
    time_id = models.CharField(blank=True, max_length=30)
    read_num = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        md = markdown.Markdown(
            extensions=[
                # 包含 缩写、表格等常用扩展
                'markdown.extensions.extra',
                # 语法高亮扩展
                'markdown.extensions.codehilite',
                # 目录扩展
                'markdown.extensions.toc',
            ]
        )
        self.content_html = md.convert(self.content)
        if not self.time_id or len(self.time_id) == 0:
            self.publish_time = datetime.datetime.now()
            self.time_id = self.publish_time.strftime("%Y%m%d") + str(random.randrange(999, 10000, 1))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-publish_time']

apps/cms/forms.py
from django import forms
from apps.post.models import Category
from apps.post.models import Post
from apps.link.models import Link
from apps.link.models import Advertise


class CategoryAddForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class CategoryEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Category
        fields = "__all__"


class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('read_num',)


class PostEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Post
        exclude = ('read_num',)


class LinkAddForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = "__all__"


class LinkEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Link
        fields = "__all__"


class AdvertiseAddForm(forms.ModelForm):
    class Meta:
        model = Advertise
        fields = "__all__"


class AdvertiseEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Advertise
        fields = "__all__"


class UserAddForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)


class UserEditForm(forms.Form):
    pk = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)

apps/cms/views.py
from django.shortcuts import render
from apps.post.models import Category
from apps.post.models import Post
from apps.bloguser.models import User
from apps.link.models import Link
from utils.paginator_helper import get_paginator, get_pagination_data
from apps.link.models import Advertise
import datetime
from apps.bloguser.models import User, UserVisit, DailyVisitNum, TotalVisitNum
from django.contrib.auth.decorators import login_required
from apps.bloguser.decorators import peekpa_login_superuser_required
from django.shortcuts import redirect, reverse
from apps.link.models import Advertise
# Create your views here.


def cms_login(request):
    if request.user.is_authenticated:  # 新添加的判断
        return redirect(reverse('cms:dashboard'))
    return render(request, 'cms/login.html')


def get_advertise():
    advertise_link = Advertise.objects.all()[0] if Advertise.objects.all().count() else None
    context = {
        'advertise_link': advertise_link
    }
    return context


def get_visitor_table(max_num):
    visitor_data = UserVisit.objects.all().order_by('-day')
    if len(visitor_data):
        visitor_data = visitor_data[:max_num]
    context = {
        'visitor_data_list': visitor_data,
    }
    return context


@login_required
def cms_dashboard(request):
    context = {}
    context.update(get_dashboard_top_data())
    context.update(get_dashboard_visitor_chart())
    context.update(get_advertise())
    context.update(get_visitor_table(10))
    context.update(get_post_table(10))  # 新增的 get_post_table 函数
    return render(request, 'cms/dashboard/home.html', context=context)


def get_post_table(max_num):
    visitor_day_data = UserVisit.objects.filter(day=datetime.datetime.now().strftime('%Y-%m-%d'), end_point__contains='/detail/')
    post_map = {}
    post_view_table_list = []
    if visitor_day_data:
        for item in visitor_day_data:
            post_id = item.end_point.split('/')[2]
            if post_id in post_map:
                post_map[post_id] += 1
            else:
                post_map[post_id] = 1
    if post_map:
        for key in post_map:
            key = key
            post_item = Post.objects.filter(time_id=key)
            if post_item:
                post_item[0].inscrease = post_map[key]
                post_view_table_list.append(post_item[0])
    if post_view_table_list:
        post_view_table_list.sort(key=lambda x: x.inscrease, reverse=True)
    if max_num > 0 and len(post_view_table_list) > max_num:
        post_view_table_list = post_view_table_list[:max_num]
    context = {
        'post_view_table_list': post_view_table_list,
    }
    return context


def get_dashboard_top_data():
    post_num = Post.objects.all().count()
    cur_date = datetime.datetime.now().strftime('%Y-%m-%d')
    day_visit_ip_set = set()
    day_visit_ip_list = UserVisit.objects.filter(day=cur_date)
    if day_visit_ip_list:
        for user_ip_item in day_visit_ip_list:
            if user_ip_item.ip_address not in day_visit_ip_set:
                day_visit_ip_set.add(user_ip_item.ip_address)
    day_visit_ip_num = len(day_visit_ip_set)
    day_visit_num = DailyVisitNum.objects.filter(day=cur_date)[0].count if DailyVisitNum.objects.filter(day=cur_date).count() else 0
    total_visit_num = TotalVisitNum.objects.all()[0].count if TotalVisitNum.objects.all().count() else 0
    context = {
        "post_num": post_num,
        "day_visit_ip_num": day_visit_ip_num,
        "day_visit_num": day_visit_num,
        "total_visit_num": total_visit_num
    }
    return context


@login_required
def category_manage_view(request):
    context = {
        "list_data": Category.objects.all()
    }
    return render(request, 'cms/category/manage.html', context=context)


@login_required
def category_publish_view(request):
    return render(request, 'cms/category/publish.html')




@login_required
def post_manage_view(request):
    page = int(request.GET.get('p', 1))
    posts = Post.objects.all()
    paginator = get_paginator(posts)
    page_obj = paginator.page(page)
    context = {
        "list_data": page_obj.object_list,
        'list_data_status': Post.STATUS_ITEMS
    }
    context.update(get_pagination_data(paginator, page_obj))
    return render(request, 'cms/post/manage.html', context=context)


@login_required
def post_publish_view(request):
    context = {
        'list_data_category': Category.objects.all(),
        'list_data_user': User.objects.all(),
        'list_data_status': Post.STATUS_ITEMS
    }
    return render(request, 'cms/post/publish.html', context=context)


@login_required
def link_manage_view(request):
    context = {
        "list_data": Link.objects.all(),
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/manage.html', context=context)


@login_required
def link_publish_view(request):
    context = {
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/publish.html', context=context)


@login_required
def advertise_manage_view(request):
    context = {
        "list_data": Advertise.objects.all()
    }
    return render(request, 'cms/advertise/manage.html', context=context)


@login_required
def advertise_publish_view(request):
    return render(request, 'cms/advertise/publish.html')


@login_required
@peekpa_login_superuser_required
def user_manage_view(request):
    context = {
        "list_data": User.objects.all(),
    }
    return render(request, 'cms/user/manage.html', context=context)


@login_required
@peekpa_login_superuser_required
def user_publish_view(request):
    return render(request, 'cms/user/publish.html')


def get_dashboard_visitor_chart():
    this_week_visit_list = []
    last_week_visit_list = []
    max_num = 0
    week_total_num = 0
    cur_day_in_week = datetime.datetime.today().weekday()
    for index in range(cur_day_in_week, -1, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        this_week_visit_list.append(day_visit_num)
        week_total_num += day_visit_num
        max_num = day_visit_num if day_visit_num > max_num else max_num
    for index in range(cur_day_in_week + 7, cur_day_in_week, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        last_week_visit_list.append(day_visit_num)
    max_num = 50 if max_num < 50 else max_num
    context = {
        'visit_week_total_number': week_total_num,
        'this_week_data_list': this_week_visit_list,
        'last_week_data_list': last_week_visit_list,
        'suggested_max': max_num
    }
    return context


def get_before_date(day):
    today = datetime.datetime.now()
    offset = datetime.timedelta(days=-day)
    re_date = (today + offset).strftime("%Y-%m-%d")
    return re_date

apps/post/views.py
from django.shortcuts import render
from apps.post.models import Post
import markdown
from apps.link.models import Link
from apps.link.models import Advertise
from django.core.cache import cache
from django.db.models import F
from apps.bloguser.tracking import peekpa_tracking
from apps.post.cache_manager import get_data_from_cache
# Create your views here.


def process_toc(toc):
    toc = toc.replace('<div class="toc">', '').replace('</div>','').replace('<ul>','<ul class="list-group">').replace('<li>','<li class="border-0 list-group-item ">')
    if len(toc) <= 31:
        toc = None
    return toc


def get_read_most_post():
    read_post = Post.objects.all().order_by('-read_num')
    if len(read_post) > 5:
        read_post = read_post[:5]
    context = {
        'read_post': read_post
    }
    return context


@peekpa_tracking
def index(request):
    context = get_data_from_cache(request, get_index_data, redis_key="post:index") # 读取缓存数据
    context.update(get_read_most_post())
    return render(request, 'post/index.html', context=context)


def get_index_data():
    top_post = Post.objects.filter(status=Post.STATUS_NORMAL, priority__gt=0).order_by('-priority')
    if len(top_post) > 4:
        top_post = top_post[:4]
    list_post = Post.objects.filter(status=Post.STATUS_NORMAL, priority=0)
    context = {
        'top_post': top_post,
        'list_post': list_post
    }
    context.update(get_link())
    context.update(get_advertise())
    return context


@peekpa_tracking
def post_list_view(request):
    context = get_data_from_cache(request, get_post_list_data, redis_key="post:post_list")
    context.update(get_read_most_post())
    return render(request, 'post/list.html', context=context)


def get_post_list_data():
    hot_post = Post.objects.filter(status=Post.STATUS_NORMAL, is_hot=True).order_by('time_id')
    list_post = Post.objects.filter(status=Post.STATUS_NORMAL, is_hot=False).order_by('time_id')
    context = {
        'hot_post': hot_post,
        'list_post': list_post,
    }
    context.update(get_link())
    context.update(get_advertise())
    return context


@peekpa_tracking
def detail(request, time_id):
    context = get_data_from_cache(request, get_detail_data, time_id=time_id)
    context.update(get_read_most_post())
    handle_visited_num(request, time_id)
    return render(request, 'post/detail.html', context=context)


def get_detail_data(time_id):
    post = Post.objects.select_related('category', 'author').get(time_id=time_id)
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    md.convert(post.content)
    context = {
        'post_data': post,
        'toc': process_toc(md.toc)
    }
    context.update(get_link())
    context.update(get_advertise())
    return context


def get_link():
    links = Link.objects.filter(status=Link.STATUS_NORMAL)
    context = {
        'link_data': links
    }
    return context


def get_advertise():
    advertise_link = Advertise.objects.all()[0] if Advertise.objects.all().count() else None
    context = {
        'advertise_link': advertise_link
    }
    return context


def handle_visited_num(request, time_id):
    increase_post_view = False
    uid = request.uid
    pv_key = 'pv:%s:%s' % (uid, request.path)
    if not cache.get(pv_key):
        increase_post_view = True
        cache.set(pv_key, 1, 2 * 60)
    if increase_post_view:
        Post.objects.filter(time_id=time_id).update(read_num=F('read_num') + 1)

front/templates/cms/post/manage.html
{% extends 'cms/base/cms_base.html' %}
{% load time_filters %}

{% block title %}
    Post Management
{% endblock %}

{% block content %}
<section class="content">
  <div class="container-fluid pt-4">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body">
            <div class="row p-2 d-flex">
              <p class="h3">文章列表</p>
              <div class="ml-auto">
                <a
                  class="btn btn-primary text-right"
                  href="{% url 'cms:post_publish_view' %}"
                  ><i class="mr-2 fas fa-plus"></i>新增</a
                >
              </div>
            </div>
            <div class="row">
              <table class="table table-bordered table-hover">
                <thead class="thead-light">
                  <tr>
                    <th style="width: 10%;">#</th>
                    <th>Title</th>
                    <th style="width: 10%;">Category</th>
                    <th style="width: 10%;">Priority</th>
                    <th style="width: 10%;">Status</th>
                    <th style="width: 10%;">Publish_Time</th>
                    <th style="width: 15%;">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in list_data %}
                  <tr>
                    <td>{{ item.id }}</td>
                    <td>
                      <a
                        href="{% url 'cms:post_edit_view' %}?post_id={{ item.id }}"
                        class=""
                        >{{ item.title }}</a
                      >
                    </td>
                    <td>{{ item.category.name }}</td>
                    <td>{{ item.priority }}</td>
                    <td>
                      {% for list_item in list_data_status %} {% if item.status == list_item.0 %} {{ list_item.1 }} {% endif %} {% endfor %}
                    </td>
                    <td>{{ item.publish_time | data_format_y_m_d }}</td>
                    <td>
                      <a
                        href="{% url 'cms:post_edit_view' %}?post_id={{ item.id }}"
                        class="btn btn-primary btn-xs"
                        >修改</a
                      >
                      <a
  href="{% url 'post:detail' time_id=item.time_id %}"
  target="_blank"
  class="btn btn-warning btn-xs"
  >预览</a
>
                      <a
                        href="{% url 'cms:post_delete' %}?post_id={{ item.id }}"
                        class="btn btn-danger btn-xs"
                        >删除</a
                      >
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
  <div class="col-sm-5">
    <p class="pull-left">第{{ current_page }}页/总共{{ num_pages }}页</p>
  </div>
  <div class="col-sm-7">
    <div class="dataTables_paginate paging_simple_numbers float-right">
      <ul class="pagination">
        {#上一页#} {% if page_obj.has_previous %}
        <li class="paginate_button page-item ">
          <a
            class="page-link"
            href="?p={{ page_obj.previous_page_number }}{{ url_query }}"
            >上一页</a
          >
        </li>
        {% else %}
        <li class="paginate_button page-item previous disabled">
          <a class="page-link" href="javascript:void(0);">上一页</a>
        </li>
        {% endif %} {# 是否需要出现三个点 #} {% if left_has_more %}
        <li class="paginate_button page-item ">
          <a class="page-link" href="?p=1">1</a>
        </li>
        <li class="paginate_button page-item ">
          <a class="page-link" href="javascript:void(0);">...</a>
        </li>
        {% endif %} {# 左边的页码 #} {% for left_page in left_pages %}
        <li class="paginate_button page-item ">
          <a class="page-link" href="?p={{ left_page }}{{ url_query }}"
            >{{ left_page }}</a
          >
        </li>
        {% endfor %} {# 当前的页面 #}
        <li class="paginate_button page-item  active">
          <a class="page-link" href="?p={{ current_page }}{{ url_query }}"
            >{{ current_page }}</a
          >
        </li>

        {# 右边的页码 #} {% for right_page in right_pages %}
        <li class="paginate_button page-item ">
          <a class="page-link" href="?p={{ right_page }}{{ url_query }}"
            >{{ right_page }}</a
          >
        </li>
        {% endfor %} {# 用来控制右边三个点 #} {% if right_has_more %}
        <li class="paginate_button page-item ">
          <a class="page-link" href="javascript:void(0);">...</a>
        </li>
        <li class="paginate_button page-item ">
          <a
            class="page-link"
            href="?p=
                            {{ num_pages }}{{ url_query }}"
            >{{ num_pages }}</a
          >
        </li>
        {% endif %} {#下一页#} {% if page_obj.has_next %}
        <li class="paginate_button page-item next">
          <a
            class="page-link"
            href="?p={{ page_obj.next_page_number }}{{ url_query }}"
            >下一页</a
          >
        </li>
        {% else %}
        <li class="paginate_button page-item next disabled">
          <a class="page-link" href="javascript:void(0);">下一页</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}