Peekpa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.bloguser.urls')),  # 新添加 BlogUser App URL 文件
    path('', include('apps.post.urls')),
]

apps/bloguser/urls.py
from django.urls import path
from . import views

app_name = "bloguser"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

apps/cms/urls.py
from django.urls import path
from . import views
from apps.cms.category_view import CategoryView
from apps.cms.category_view import CategoryEditView
from apps.cms.category_view import CategoryDeleteView
from apps.cms.post_view import PostView
from apps.cms.post_view import PostEditView
from apps.cms.post_view import PostDeleteView
from .link_view import LinkView
from .link_view import LinkEditView
from .link_view import LinkDeleteView
from .advertise_view import AdvertiseView
from .advertise_view import AdvertiseEditView
from .advertise_view import AdvertiseDeleteView
from .user_view import UserView
from .user_view import UserEditView
from .user_view import UserDeleteView

app_name = "cms"

urlpatterns = [
    path("login/", views.cms_login, name="login"),
    path("dashboard/", views.cms_dashboard, name="dashboard"),
    path("dashboard/category/manage", views.category_manage_view, name="category_manage_view"),
    path("dashboard/category/publish", views.category_publish_view, name="category_publish_view"),
    path("dashboard/category/add", CategoryView.as_view(), name="category_add"),
    path("dashboard/category/edit", CategoryEditView.as_view(), name="category_edit_view"),
    path("dashboard/category/delete", CategoryDeleteView.as_view(), name="category_delete"),
    path("dashboard/post/manage", views.post_manage_view, name="post_manage_view"),
    path("dashboard/post/publish", views.post_publish_view, name="post_publish_view"),
    path("dashboard/post/add", PostView.as_view(), name="post_add"),
    path("dashboard/post/edit", PostEditView.as_view(), name="post_edit_view"),
    path("dashboard/post/delete", PostDeleteView.as_view(), name="post_delete"),
    path("dashboard/link/manage", views.link_manage_view, name="link_manage_view"),
    path("dashboard/link/publish", views.link_publish_view, name="link_publish_view"),
    path("dashboard/link/add", LinkView.as_view(), name="link_add"),
    path("dashboard/link/edit", LinkEditView.as_view(), name="link_edit_view"),
    path("dashboard/link/delete", LinkDeleteView.as_view(), name="link_delete"),
    path("dashboard/advertise/manage", views.advertise_manage_view, name="advertise_manage_view"),
    path("dashboard/advertise/publish", views.advertise_publish_view, name="advertise_publish_view"),
    path("dashboard/advertise/add", AdvertiseView.as_view(), name="advertise_add"),
    path("dashboard/advertise/edit", AdvertiseEditView.as_view(), name="advertise_edit_view"),
    path("dashboard/advertise/delete", AdvertiseDeleteView.as_view(), name="advertise_delete"),
    path("dashboard/user/manage", views.user_manage_view, name="user_manage_view"),
    path("dashboard/user/publish", views.user_publish_view, name="user_publish_view"),
    path("dashboard/user/add", UserView.as_view(), name="user_add"),
    path("dashboard/user/edit", UserEditView.as_view(), name="user_edit_view"),
    path("dashboard/user/delete", UserDeleteView.as_view(), name="user_delete"),
]

apps/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name="index"),
    path("list/", views.post_list_view, name="post_list"),
    path("detail/<int:time_id>/", views.detail, name="detail"),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from django import forms
from apps.post.models import Category
from apps.post.models import Post
from apps.link.models import Link
from apps.link.models import Advertise


class CategoryAddForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class CategoryEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Category
        fields = "__all__"


class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('read_num',)


class PostEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Post
        exclude = ('read_num',)


class LinkAddForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = "__all__"


class LinkEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Link
        fields = "__all__"


class AdvertiseAddForm(forms.ModelForm):
    class Meta:
        model = Advertise
        fields = "__all__"


class AdvertiseEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Advertise
        fields = "__all__"


class UserAddForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)


class UserEditForm(forms.Form):
    pk = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)

apps/cms/views.py
from django.shortcuts import render
from apps.post.models import Category
from apps.post.models import Post
from apps.bloguser.models import User
from apps.link.models import Link
from utils.paginator_helper import get_paginator, get_pagination_data
from apps.link.models import Advertise
import datetime
from apps.bloguser.models import User, UserVisit, DailyVisitNum, TotalVisitNum
from django.contrib.auth.decorators import login_required
from apps.bloguser.decorators import peekpa_login_superuser_required
from django.shortcuts import redirect, reverse
from apps.link.models import Advertise
# Create your views here.


def cms_login(request):
    if request.user.is_authenticated:  # 新添加的判断
        return redirect(reverse('cms:dashboard'))
    return render(request, 'cms/login.html')


def get_advertise():
    advertise_link = Advertise.objects.all()[0] if Advertise.objects.all().count() else None
    context = {
        'advertise_link': advertise_link
    }
    return context


def get_visitor_table(max_num):
    visitor_data = UserVisit.objects.all().order_by('-day')
    if len(visitor_data):
        visitor_data = visitor_data[:max_num]
    context = {
        'visitor_data_list': visitor_data,
    }
    return context


@login_required
def cms_dashboard(request):
    context = {}
    context.update(get_dashboard_top_data())
    context.update(get_dashboard_visitor_chart())
    context.update(get_advertise())
    context.update(get_visitor_table(10))
    context.update(get_post_table(10))  # 新增的 get_post_table 函数
    return render(request, 'cms/dashboard/home.html', context=context)


def get_post_table(max_num):
    visitor_day_data = UserVisit.objects.filter(day=datetime.datetime.now().strftime('%Y-%m-%d'), end_point__contains='/detail/')
    post_map = {}
    post_view_table_list = []
    if visitor_day_data:
        for item in visitor_day_data:
            post_id = item.end_point.split('/')[2]
            if post_id in post_map:
                post_map[post_id] += 1
            else:
                post_map[post_id] = 1
    if post_map:
        for key in post_map:
            key = key
            post_item = Post.objects.filter(time_id=key)
            if post_item:
                post_item[0].inscrease = post_map[key]
                post_view_table_list.append(post_item[0])
    if post_view_table_list:
        post_view_table_list.sort(key=lambda x: x.inscrease, reverse=True)
    if max_num > 0 and len(post_view_table_list) > max_num:
        post_view_table_list = post_view_table_list[:max_num]
    context = {
        'post_view_table_list': post_view_table_list,
    }
    return context


def get_dashboard_top_data():
    post_num = Post.objects.all().count()
    cur_date = datetime.datetime.now().strftime('%Y-%m-%d')
    day_visit_ip_set = set()
    day_visit_ip_list = UserVisit.objects.filter(day=cur_date)
    if day_visit_ip_list:
        for user_ip_item in day_visit_ip_list:
            if user_ip_item.ip_address not in day_visit_ip_set:
                day_visit_ip_set.add(user_ip_item.ip_address)
    day_visit_ip_num = len(day_visit_ip_set)
    day_visit_num = DailyVisitNum.objects.filter(day=cur_date)[0].count if DailyVisitNum.objects.filter(day=cur_date).count() else 0
    total_visit_num = TotalVisitNum.objects.all()[0].count if TotalVisitNum.objects.all().count() else 0
    context = {
        "post_num": post_num,
        "day_visit_ip_num": day_visit_ip_num,
        "day_visit_num": day_visit_num,
        "total_visit_num": total_visit_num
    }
    return context


@login_required
def category_manage_view(request):
    context = {
        "list_data": Category.objects.all()
    }
    return render(request, 'cms/category/manage.html', context=context)


@login_required
def category_publish_view(request):
    return render(request, 'cms/category/publish.html')




@login_required
def post_manage_view(request):
    page = int(request.GET.get('p', 1))
    posts = Post.objects.all()
    paginator = get_paginator(posts)
    page_obj = paginator.page(page)
    context = {
        "list_data": page_obj.object_list,
        'list_data_status': Post.STATUS_ITEMS
    }
    context.update(get_pagination_data(paginator, page_obj))
    return render(request, 'cms/post/manage.html', context=context)


@login_required
def post_publish_view(request):
    context = {
        'list_data_category': Category.objects.all(),
        'list_data_user': User.objects.all(),
        'list_data_status': Post.STATUS_ITEMS
    }
    return render(request, 'cms/post/publish.html', context=context)


@login_required
def link_manage_view(request):
    context = {
        "list_data": Link.objects.all(),
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/manage.html', context=context)


@login_required
def link_publish_view(request):
    context = {
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/publish.html', context=context)


@login_required
def advertise_manage_view(request):
    context = {
        "list_data": Advertise.objects.all()
    }
    return render(request, 'cms/advertise/manage.html', context=context)


@login_required
def advertise_publish_view(request):
    return render(request, 'cms/advertise/publish.html')


@login_required
@peekpa_login_superuser_required
def user_manage_view(request):
    context = {
        "list_data": User.objects.all(),
    }
    return render(request, 'cms/user/manage.html', context=context)


@login_required
@peekpa_login_superuser_required
def user_publish_view(request):
    return render(request, 'cms/user/publish.html')


def get_dashboard_visitor_chart():
    this_week_visit_list = []
    last_week_visit_list = []
    max_num = 0
    week_total_num = 0
    cur_day_in_week = datetime.datetime.today().weekday()
    for index in range(cur_day_in_week, -1, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        this_week_visit_list.append(day_visit_num)
        week_total_num += day_visit_num
        max_num = day_visit_num if day_visit_num > max_num else max_num
    for index in range(cur_day_in_week + 7, cur_day_in_week, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        last_week_visit_list.append(day_visit_num)
    max_num = 50 if max_num < 50 else max_num
    context = {
        'visit_week_total_number': week_total_num,
        'this_week_data_list': this_week_visit_list,
        'last_week_data_list': last_week_visit_list,
        'suggested_max': max_num
    }
    return context


def get_before_date(day):
    today = datetime.datetime.now()
    offset = datetime.timedelta(days=-day)
    re_date = (today + offset).strftime("%Y-%m-%d")
    return re_date

front/templates/cms/base/cms_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title> MengOS | CMS | {% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Ionicons -->
    <link
      rel="stylesheet"
      href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    />
    <!-- Tempusdominus Bbootstrap 4 -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}"
    />
    <!-- iCheck -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"
    />
    <!-- Theme style -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/dist/css/adminlte.min.css' %}"
    />
    <!-- overlayScrollbars -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
    />
    <!-- Daterange picker -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/daterangepicker/daterangepicker.css' %}"
    />
    <!-- summernote -->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/plugins/summernote/summernote-bs4.css' %}"
    />
    <!-- Google Font: Source Sans Pro -->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
      rel="stylesheet"
    />
    {% block head %} {% endblock %}
  <!-- jQuery -->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
  </head>
  <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
      <!-- Navbar -->
      {% include 'cms/base/navbar.html' %}

      <!-- Sidebar-->
      {% include 'cms/base/sidebar.html' %}

      <div class="content-wrapper">{% block content %} {% endblock %}</div>
    </div>


    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge("uibutton", $.ui.button);
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'adminlte/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'adminlte/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.js' %}"></script>
    {% block script %} {% endblock %}
  </body>
</html>

front/templates/cms/base/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'post:index' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>
  <a
    href="{% url 'bloguser:logout' %}"
    class="text-decoration-none text-dark ml-auto nav-link"
  >
    {% if request.user.is_superuser %}
        {{ request.user.username }}
    {% else %}
        Hello <b class="text-danger">{{ request.user.username }}</b>
    {% endif %}
     , Logout</a
  ><!-- 新添加代码 -->
</nav>

front/templates/cms/base/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="{% url 'cms:dashboard' %}" class="brand-link">
    <img
      src="{% static 'image/cms_logo.png' %}"
      class="brand-image img-circle elevation-3"
      style="opacity: .8"
    />
    <span class="brand-text font-weight-light">zrm343 管理系统</span>
  </a>

  <div class="sidebar">
    <nav class="mt-2">
      <ul
        class="nav nav-pills nav-sidebar flex-column"
        data-widget="treeview"
        role="menu"
        data-accordion="false"
      >
        {% url 'cms:dashboard' as cms_home_page %}
        <li class="nav-item">
          <a
            href="{{ cms_home_page }}"
            class="nav-link {% if request.path == cms_home_page %}active{% endif %}"
          >
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>控制台</p>
          </a>
        </li>
        {% url 'cms:category_manage_view' as category_manage_view %}
{% url 'cms:category_publish_view' as category_publish_view %}
{% url 'cms:category_edit_view' as category_edit_view %}
<li
  class="nav-item has-treeview {% if request.path == category_manage_view or request.path == category_publish_view or request.path == category_edit_view %}menu-open{% endif %}"
>
  <a
    href="#"
    class="nav-link {% if request.path == category_manage_view or request.path == category_publish_view or request.path == category_edit_view %}active{% endif %}"
  >
    <i class="nav-icon far fa-bookmark"></i>
    <p>
      分类标签
      <i class="right fas fa-angle-left"></i>
    </p>
  </a>
  <ul class="nav nav-treeview">
    <li class="nav-item">
      <a
        href="{{ category_manage_view }}"
        class="nav-link {% if request.path == category_manage_view or request.path == category_edit_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>标签列表</p>
      </a>
    </li>
    <li class="nav-item">
      <a
        href="{{ category_publish_view }}"
        class="nav-link {% if request.path == category_publish_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>标签发布</p>
      </a>
    </li>
  </ul>
</li>

{#      文章管理#}
{% url 'cms:post_manage_view' as post_manage_view %}
{% url 'cms:post_publish_view' as post_publish_view %}
{% url 'cms:post_edit_view' as post_edit_view %}
<li
  class="nav-item has-treeview {% if request.path == post_manage_view or request.path == post_publish_view or request.path == post_edit_view %}menu-open{% endif %}"
>
  <a
    href="{{ post_manage_view }}"
    class="nav-link {% if request.path == post_manage_view or request.path == post_publish_view or request.path == post_edit_view %}active{% endif %}"
  >
    <i class="nav-icon far fa-copy"></i>
    <p>
      文章管理
      <i class="right fas fa-angle-left"></i>
    </p>
  </a>
  <ul class="nav nav-treeview">
    <li class="nav-item">
      <a
        href="{{ post_manage_view }}"
        class="nav-link {% if request.path == post_manage_view or request.path == post_edit_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>文章列表</p>
      </a>
    </li>
    <li class="nav-item">
      <a
        href="{{ post_publish_view }}"
        class="nav-link {% if request.path == post_publish_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>文章发布</p>
      </a>
    </li>
  </ul>
</li>

{#      友链管理#}
      {% url 'cms:link_manage_view' as link_manage_view %}
{% url 'cms:link_publish_view' as link_publish_view %}
{% url 'cms:link_edit_view' as link_edit_view %} <!-- 新添加修改代码 -->
<li
  class="nav-item has-treeview {% if request.path == link_manage_view or request.path == link_publish_view or request.path == link_edit_view %}menu-open{% endif %}"
> <!-- 新添加修改代码 -->
  <a
    href="#"
    class="nav-link {% if request.path == link_manage_view or request.path == link_publish_view or request.path == link_edit_view %}active{% endif %}"
  > <!-- 新添加修改代码 -->
    <i class="nav-icon fas fa-link"></i>
    <p>
      友链管理
      <i class="right fas fa-angle-left"></i>
    </p>
  </a>
  <ul class="nav nav-treeview">
    <li class="nav-item">
      <a
        href="{% url 'cms:link_manage_view' %}"
        class="nav-link {% if request.path == link_manage_view %}active{% endif %}"
      > <!-- 新添加修改代码 -->
        <i class="far fa-circle nav-icon"></i>
        <p>友链列表</p>
      </a>
    </li>
    <li class="nav-item">
      <a
        href="{% url 'cms:link_publish_view' %}"
        class="nav-link {% if request.path == link_publish_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>新建友链</p>
      </a>
    </li>
  </ul>
</li>

{#      广告管理#}
     {% url 'cms:advertise_manage_view' as advertise_manage_view %}
          {% url 'cms:advertise_publish_view' as advertise_publish_view %}
          {% url 'cms:advertise_edit_view' as advertise_edit_view %}
<!-- 新添加修改代码 -->
<li
  class="nav-item has-treeview {% if request.path == advertise_manage_view or request.path == advertise_publish_view or request.path == advertise_edit_view %}menu-open{% endif %}"
>
  <!-- 新添加修改代码 -->
  <a
    href="#"
    class="nav-link {% if request.path == advertise_manage_view or request.path == advertise_publish_view or request.path == advertise_edit_view %}active{% endif %}"
  >
    <!-- 新添加修改代码 -->
    <i class="nav-icon fas fa-ad"></i>
    <p>
      广告管理
      <i class="right fas fa-angle-left"></i>
    </p>
  </a>
  <ul class="nav nav-treeview">
    <li class="nav-item">
      <a
        href="{% url 'cms:advertise_manage_view' %}"
        class="nav-link {% if request.path == advertise_manage_view or request.path == advertise_edit_view %}active{% endif %}"
      >
        <!-- 新添加修改代码 -->
        <i class="far fa-circle nav-icon"></i>
        <p>广告列表</p>
      </a>
    </li>
    <li class="nav-item">
      <a
        href="{% url 'cms:advertise_publish_view' %}"
        class="nav-link {% if request.path == advertise_publish_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>新建广告</p>
      </a>
    </li>
  </ul>
</li>
{#用户管理#}
      {% if request.user.is_superuser %}
    {% url 'cms:user_manage_view' as user_manage_view %}
    {% url 'cms:user_publish_view' as user_publish_view %}
    {% url 'cms:user_edit_view' as user_edit_view%}
    <li class="nav-item has-treeview {% if request.path == user_manage_view or request.path == user_publish_view  or request.path == user_edit_view %}menu-open{% endif %}">
        <a href="#"
            class="nav-link {% if request.path == user_manage_view or request.path == user_publish_view or request.path == user_edit_view %}active{% endif %}">
            <i class="nav-icon fas fa-user"></i>
            <p>
                用户管理
                <i class="right fas fa-angle-left"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
      <a
        href="{% url 'cms:user_manage_view' %}"
        class="nav-link {% if request.path == user_manage_view  or request.path == user_edit_view %}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>用户列表</p>
      </a>
    </li>
    <li class="nav-item">
      <a
        href="{% url 'cms:user_publish_view' %}"
        class="nav-link {% if request.path == user_publish_view%}active{% endif %}"
      >
        <i class="far fa-circle nav-icon"></i>
        <p>新建用户</p>
      </a>
    </li>
  </ul>
</li>
{% endif %}
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>