Peekpa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.bloguser.urls')),  # 新添加 BlogUser App URL 文件
    path('', include('apps.post.urls')),
]

apps/cms/urls.py
from django.urls import path
from . import views
from apps.cms.category_view import CategoryView
from apps.cms.category_view import CategoryEditView
from apps.cms.category_view import CategoryDeleteView
from apps.cms.post_view import PostView
from apps.cms.post_view import PostEditView
from apps.cms.post_view import PostDeleteView
from .link_view import LinkView
from .link_view import LinkEditView
from .link_view import LinkDeleteView
from .advertise_view import AdvertiseView
from .advertise_view import AdvertiseEditView
from .advertise_view import AdvertiseDeleteView
from .user_view import UserView
from .user_view import UserEditView
from .user_view import UserDeleteView

app_name = "cms"

urlpatterns = [
    path("login/", views.cms_login, name="login"),
    path("dashboard/", views.cms_dashboard, name="dashboard"),
    path("dashboard/category/manage", views.category_manage_view, name="category_manage_view"),
    path("dashboard/category/publish", views.category_publish_view, name="category_publish_view"),
    path("dashboard/category/add", CategoryView.as_view(), name="category_add"),
    path("dashboard/category/edit", CategoryEditView.as_view(), name="category_edit_view"),
    path("dashboard/category/delete", CategoryDeleteView.as_view(), name="category_delete"),
    path("dashboard/post/manage", views.post_manage_view, name="post_manage_view"),
    path("dashboard/post/publish", views.post_publish_view, name="post_publish_view"),
    path("dashboard/post/add", PostView.as_view(), name="post_add"),
    path("dashboard/post/edit", PostEditView.as_view(), name="post_edit_view"),
    path("dashboard/post/delete", PostDeleteView.as_view(), name="post_delete"),
    path("dashboard/link/manage", views.link_manage_view, name="link_manage_view"),
    path("dashboard/link/publish", views.link_publish_view, name="link_publish_view"),
    path("dashboard/link/add", LinkView.as_view(), name="link_add"),
    path("dashboard/link/edit", LinkEditView.as_view(), name="link_edit_view"),
    path("dashboard/link/delete", LinkDeleteView.as_view(), name="link_delete"),
    path("dashboard/advertise/manage", views.advertise_manage_view, name="advertise_manage_view"),
    path("dashboard/advertise/publish", views.advertise_publish_view, name="advertise_publish_view"),
    path("dashboard/advertise/add", AdvertiseView.as_view(), name="advertise_add"),
    path("dashboard/advertise/edit", AdvertiseEditView.as_view(), name="advertise_edit_view"),
    path("dashboard/advertise/delete", AdvertiseDeleteView.as_view(), name="advertise_delete"),
    path("dashboard/user/manage", views.user_manage_view, name="user_manage_view"),
    path("dashboard/user/publish", views.user_publish_view, name="user_publish_view"),
    path("dashboard/user/add", UserView.as_view(), name="user_add"),
    path("dashboard/user/edit", UserEditView.as_view(), name="user_edit_view"),
    path("dashboard/user/delete", UserDeleteView.as_view(), name="user_delete"),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from django import forms
from apps.post.models import Category
from apps.post.models import Post
from apps.link.models import Link
from apps.link.models import Advertise


class CategoryAddForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class CategoryEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Category
        fields = "__all__"


class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('read_num',)


class PostEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Post
        exclude = ('read_num',)


class LinkAddForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = "__all__"


class LinkEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Link
        fields = "__all__"


class AdvertiseAddForm(forms.ModelForm):
    class Meta:
        model = Advertise
        fields = "__all__"


class AdvertiseEditForm(forms.ModelForm):
    pk = forms.CharField(max_length=100)

    class Meta:
        model = Advertise
        fields = "__all__"


class UserAddForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)


class UserEditForm(forms.Form):
    pk = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(max_length=20, min_length=6)

apps/cms/views.py
from django.shortcuts import render
from apps.post.models import Category
from apps.post.models import Post
from apps.bloguser.models import User
from apps.link.models import Link
from utils.paginator_helper import get_paginator, get_pagination_data
from apps.link.models import Advertise
import datetime
from apps.bloguser.models import User, UserVisit, DailyVisitNum, TotalVisitNum
from django.contrib.auth.decorators import login_required
from apps.bloguser.decorators import peekpa_login_superuser_required
from django.shortcuts import redirect, reverse
from apps.link.models import Advertise
# Create your views here.


def cms_login(request):
    if request.user.is_authenticated:  # 新添加的判断
        return redirect(reverse('cms:dashboard'))
    return render(request, 'cms/login.html')


def get_advertise():
    advertise_link = Advertise.objects.all()[0] if Advertise.objects.all().count() else None
    context = {
        'advertise_link': advertise_link
    }
    return context


def get_visitor_table(max_num):
    visitor_data = UserVisit.objects.all().order_by('-day')
    if len(visitor_data):
        visitor_data = visitor_data[:max_num]
    context = {
        'visitor_data_list': visitor_data,
    }
    return context


@login_required
def cms_dashboard(request):
    context = {}
    context.update(get_dashboard_top_data())
    context.update(get_dashboard_visitor_chart())
    context.update(get_advertise())
    context.update(get_visitor_table(10))
    context.update(get_post_table(10))  # 新增的 get_post_table 函数
    return render(request, 'cms/dashboard/home.html', context=context)


def get_post_table(max_num):
    visitor_day_data = UserVisit.objects.filter(day=datetime.datetime.now().strftime('%Y-%m-%d'), end_point__contains='/detail/')
    post_map = {}
    post_view_table_list = []
    if visitor_day_data:
        for item in visitor_day_data:
            post_id = item.end_point.split('/')[2]
            if post_id in post_map:
                post_map[post_id] += 1
            else:
                post_map[post_id] = 1
    if post_map:
        for key in post_map:
            key = key
            post_item = Post.objects.filter(time_id=key)
            if post_item:
                post_item[0].inscrease = post_map[key]
                post_view_table_list.append(post_item[0])
    if post_view_table_list:
        post_view_table_list.sort(key=lambda x: x.inscrease, reverse=True)
    if max_num > 0 and len(post_view_table_list) > max_num:
        post_view_table_list = post_view_table_list[:max_num]
    context = {
        'post_view_table_list': post_view_table_list,
    }
    return context


def get_dashboard_top_data():
    post_num = Post.objects.all().count()
    cur_date = datetime.datetime.now().strftime('%Y-%m-%d')
    day_visit_ip_set = set()
    day_visit_ip_list = UserVisit.objects.filter(day=cur_date)
    if day_visit_ip_list:
        for user_ip_item in day_visit_ip_list:
            if user_ip_item.ip_address not in day_visit_ip_set:
                day_visit_ip_set.add(user_ip_item.ip_address)
    day_visit_ip_num = len(day_visit_ip_set)
    day_visit_num = DailyVisitNum.objects.filter(day=cur_date)[0].count if DailyVisitNum.objects.filter(day=cur_date).count() else 0
    total_visit_num = TotalVisitNum.objects.all()[0].count if TotalVisitNum.objects.all().count() else 0
    context = {
        "post_num": post_num,
        "day_visit_ip_num": day_visit_ip_num,
        "day_visit_num": day_visit_num,
        "total_visit_num": total_visit_num
    }
    return context


@login_required
def category_manage_view(request):
    context = {
        "list_data": Category.objects.all()
    }
    return render(request, 'cms/category/manage.html', context=context)


@login_required
def category_publish_view(request):
    return render(request, 'cms/category/publish.html')




@login_required
def post_manage_view(request):
    page = int(request.GET.get('p', 1))
    posts = Post.objects.all()
    paginator = get_paginator(posts)
    page_obj = paginator.page(page)
    context = {
        "list_data": page_obj.object_list,
        'list_data_status': Post.STATUS_ITEMS
    }
    context.update(get_pagination_data(paginator, page_obj))
    return render(request, 'cms/post/manage.html', context=context)


@login_required
def post_publish_view(request):
    context = {
        'list_data_category': Category.objects.all(),
        'list_data_user': User.objects.all(),
        'list_data_status': Post.STATUS_ITEMS
    }
    return render(request, 'cms/post/publish.html', context=context)


@login_required
def link_manage_view(request):
    context = {
        "list_data": Link.objects.all(),
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/manage.html', context=context)


@login_required
def link_publish_view(request):
    context = {
        'list_data_status': Link.STATUS_ITEMS
    }
    return render(request, 'cms/link/publish.html', context=context)


@login_required
def advertise_manage_view(request):
    context = {
        "list_data": Advertise.objects.all()
    }
    return render(request, 'cms/advertise/manage.html', context=context)


@login_required
def advertise_publish_view(request):
    return render(request, 'cms/advertise/publish.html')


@login_required
@peekpa_login_superuser_required
def user_manage_view(request):
    context = {
        "list_data": User.objects.all(),
    }
    return render(request, 'cms/user/manage.html', context=context)


@login_required
@peekpa_login_superuser_required
def user_publish_view(request):
    return render(request, 'cms/user/publish.html')


def get_dashboard_visitor_chart():
    this_week_visit_list = []
    last_week_visit_list = []
    max_num = 0
    week_total_num = 0
    cur_day_in_week = datetime.datetime.today().weekday()
    for index in range(cur_day_in_week, -1, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        this_week_visit_list.append(day_visit_num)
        week_total_num += day_visit_num
        max_num = day_visit_num if day_visit_num > max_num else max_num
    for index in range(cur_day_in_week + 7, cur_day_in_week, -1):
        day_format_string = get_before_date(index)
        day_visit_num = 0
        daynumber_item = DailyVisitNum.objects.filter(day=day_format_string)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        last_week_visit_list.append(day_visit_num)
    max_num = 50 if max_num < 50 else max_num
    context = {
        'visit_week_total_number': week_total_num,
        'this_week_data_list': this_week_visit_list,
        'last_week_data_list': last_week_visit_list,
        'suggested_max': max_num
    }
    return context


def get_before_date(day):
    today = datetime.datetime.now()
    offset = datetime.timedelta(days=-day)
    re_date = (today + offset).strftime("%Y-%m-%d")
    return re_date

front/templates/cms/category/manage.html
{% extends 'cms/base/cms_base.html' %}

{% block title %}
    Category Management
{% endblock %}
{% block content %}
<section class="content">
  <div class="container-fluid pt-4">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body">
            <div class="row p-2 d-flex justify-content-between">
              <p class="h3">分类标签管理</p>
              <div class="float-right">
                <a
  class="btn btn-primary text-right"
  href="{% url 'cms:category_publish_view' %}"
  ><i class="mr-2 fas fa-plus"></i>新增</a
>
              </div>
            </div>
            <table class="table table-bordered table-hover">
              <thead class="thead-light">
                <tr>
                  <th style="width: 10%;">#</th>
                  <th>category_name</th>
                  <th>create_time</th>
                  <th class="w-25">actions</th>
                </tr>
              </thead>
              <tbody>
                {% for item in list_data %}
                <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.name }}</td>
                  <td>{{ item.create_time }}</td>
                  <td>
                    <a
  href="{% url 'cms:category_edit_view' %}?category_id={{ item.id }}"
  class="btn btn-info btn-xs"
  >修改</a
>
                    <a href="{% url 'cms:category_delete' %}?category_id={{ item.id }}" class="btn btn-danger btn-xs">删除</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

front/templates/cms/category/publish.html
{% extends 'cms/base/cms_base.html' %}

{% block title %}
    Category Publish
{% endblock %}

{% block content %}
<section class="content">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center pt-4">
      <div class="col-sm-6">
        <div class="card card-primary">
          <div class="card-header">
            {% if item_data %}
            <h3 class="card-title">分类标签修改</h3>
            {% else %}
            <h3 class="card-title">分类标签新增</h3>
            {% endif %}
          </div>
          <form
            class="form-horizontal"
            action="{% url 'cms:category_add' %}"
            method="post"
          >
            {% csrf_token %} {% if item_data %}
            <input
              type="text"
              class="form-control"
              id="pk"
              name="pk"
              value="{{ item_data.id }}"
              hidden
            />
            {% endif %}
            <div class="card-body">
              <div class="form-group row mb-0">
                <label for="name" class="col-form-label col-sm-2 text-center"
                  >Name</label
                >
                <div class="col-sm-10">
                  {% if item_data %}
                  <input
                    type="text"
                    class="form-control"
                    id="name"
                    name="name"
                    value="{{ item_data.name }}"
                  />
                  {% else %}
                  <input
                    type="text"
                    class="form-control"
                    id="name"
                    name="name"
                  />
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="card-footer">
              {% if item_data %}
              <button type="submit" class="btn btn-info" name="modify">
                确认
              </button>
              <button
                type="submit"
                class="btn btn-danger float-right"
                name="cancel"
              >
                取消
              </button>
              {% else %}
              <button type="submit" class="btn btn-primary" name="submit">
                确认
              </button>
              <button
                type="submit"
                class="btn btn-danger float-right"
                name="back"
              >
                返回
              </button>
              {% endif %}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}